# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test
  
    steps:
        - uses: actions/checkout@v2
        - name: Build production application
          uses: actions/setup-node@v2
          with:
            node-version: 14.x
            cache: 'npm'
        - run: npm ci
        - run: npm run build:prod
        - run: pwd
        - name: Archive Production Artifact
          uses: actions/upload-artifact@master
          with:
            name: build
            path: ./build

 deploy-functions:
   name: deploy functions
   runs-on: ubuntu-latest
   steps:
     - name: set environment variables
       uses: w9jds/firebase-action@master
       with:
         args: 'functions:config:set env.project_id:"SOME_ID" env.datastore:"THE_DATASTORE"'
       env:
         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: deploy functions
      uses: w9jds/firebase-action@master
      with:
        args: 'deploy --only functions'
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: prod
          BQ_ID: "BIG QUERY ID HERE"

 deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: ./build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: prod